name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  deploy:
    uses: WPUserManager/.github/.github/workflows/deploy.yml@master
    with:
      plugin-slug: wpum-newsletter
    secrets: inherit
